### ISSUE TITLE
Scrolling on the documentation website doesn't work.

### ISSUE THREAD

**Issue by Someoneamzing** [electron/electronjs.org-new#176] opened 2022-02-14 05:11 UTC
When scrolling on the documentation website, any attempt to scroll the page anymore than a few lines results in the page snapping back to the top. Not even manually dragging the scrollbar stops it.

It appears to be something related to the sticky navbar at the top, as the visual distance before it snaps back seems to be inline with the top of the page going past to top of the screen.

**Comment by erickzhao** [comment] 2022-02-14 19:47
@Someoneamzing I can't reproduce this locally on https://www.electronjs.org/docs/latest/. Can you share more information on your OS/web browser? A desktop recording showing a repro might help too.

**Comment by Gerigot** [comment] 2022-03-03 19:01
I have the same Issue on Chrome Version 99.0.4844.51 on Ubuntu 21.10. I've tried on Firefox and it works without problems.
I've found that if I remove the eventListener on document's scroll done by the useTOCHighlight (see the picture) it works on chrome but I've to remove it every time I change a page.
![image](https://user-images.githubusercontent.com/13289669/156633735-a4f73258-a91a-49d7-953f-537678ba0334.png)

**Comment by erickzhao** [comment] 2022-03-15 02:32
@Gerigot try forking this branch: https://github.com/electron/electronjs.org-new/pull/191

Currently blocked on the V3 migration due to some size limits that the V3 crawler infra has.

**Comment by Gerigot** [comment] 2022-03-23 20:07
> @Gerigot try forking this branch: #191
> 
> Currently blocked on the V3 migration due to some size limits that the V3 crawler infra has.

Sorry for the late reply I couldn't try before.
I've seen that the forked branch mentioned in your comment has been merged to the main branch and now the scrolling is working also in "production" (website).
I cannot reproduce the bug anymore.

**Comment by molant** [comment] 2022-03-23 21:03
Going to close this issue then!

@Someoneamzing if you are still having this issue please let us know!

**Closed by molant** 2022-03-23 21:03 UTC
